version: '3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_DB: blogdb
      POSTGRES_USER: bloguser
      POSTGRES_PASSWORD: secret123
  web:
    build: .
    environment:
      DATABASE_NAME: blogdb
      DATABASE_USER: bloguser
      DATABASE_PASSWD: secret123
      DATABASE_HOST: database
    ports:
      - 8000:8000
    command: ["./wait-for-it.sh", "database:5432", "--", "./docker-entry.sh"]
    depends_on:
      - database
