version: '3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_DB: blogdb
      POSTGRES_USER: bloguser
      POSTGRES_PASSWORD: secret123
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:  
        constraints: [node.role == manager]

  web:
    image: someone/django-blog
    environment:
      DATABASE_NAME: blogdb
      DATABASE_USER: bloguser
      DATABASE_PASSWD: secret123
      DATABASE_HOST: database
    ports:
      - 8000:8000
    command: ["./wait-for-it.sh", "database:5432", "--", "./docker-entry.sh"]
    depends_on:
      - database
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
  
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]    

